
const map = {
  LDBTC: "BTC",
  LDBUSD: "BUSD",
  LDUSDT: "USDT",
  LD1INCH: "1INCH",
  LDADA: "ADA",
  LDALGO: "ALGO",
  LDARK: "ARK",
  LDARPA: "ARPA",
  LDATOM: "ATOM",
  LDBAKE: "BAKE",
  LDBAL: "BAL",
  LDBAT: "BAT",
  LDBCH: "BCH",
  LDBRL: "BRL",
  LDCOTI: "COTI",
  LDCVC: "CVC",
  LDDAI: "DAI",
  LDDASH: "DASH",
  LDDOGE: "DOGE",
  LDDOT: "DOT",
  LDEGLD: "EGLD",
  LDEOS: "EOS",
  LDETC: "ETC",
  LDETH: "ETH",
  LDEUR: "EUR",
  LDFET: "FET",
  LDFIL: "FIL",
  LDGBP: "GBP",
  LDIOST: "IOST",
  LDIOTA: "IOTA",
  LDBNB: "BNB",
  LDKAVA: "KAVA",
  LDKMD: "KMD",
  LDKNC: "KNC",
  LDLINK: "LINK",
  LDLOOM: "LOOM",
  LDLSK: "LSK",
  LDLTC: "LTC",
  LDNEO: "NEO",
  LDONE: "ONE",
  LDONT: "ONT",
  LDQTUM: "QTUM",
  LDRUB: "RUB",
  LDSTRAT: "STRAT",
  LDSXP: "SXP",
  LDTHETA: "THETA",
};

export default function SymbolMapper(symbol: string): string {
    // @ts-ignore
  return map[symbol] || symbol;
}

